version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  web1:
    image: mardini0803/go_search_engine_client
    ports:
      - 8081:8080
    depends_on:
      - elasticsearch

  web2:
    image: mardini0803/go_search_engine_client
    ports:
      - 8082:8080
    depends_on:
      - elasticsearch

  haproxy:
    build: ./haproxy
    ports:
        - 8080:8080
    depends_on:
      - web1
      - web2
